#!/usr/bin/env bash

set -u
set -e

# Build geth before harness; the latter depends on the former.
NAMES=(quorum-raft quorum-stack quorum-constellation quorum-harness)
DIRS=(./docker-quorum/ ./docker-stack/ ./docker-constellation/ ./docker-harness/)
SECRETS=(id_noirqs github.pub)

for i in `seq 0 3`
do
  for secret in ${SECRETS[@]}
  do
    cp credentials/${secret} ${DIRS[$i]}
  done

  docker build -t ${NAMES[$i]} ${DIRS[$i]}

  for secret in ${SECRETS[@]}
  do
    rm ${DIRS[$i]}${secret}
  done
done
