#!/usr/bin/env sh

set -u
set -e

cp credentials/id_noirqs docker-quorum/
cp credentials/id_noirqs docker-harness/
cp credentials/github.pub docker-quorum/
cp credentials/github.pub docker-harness/

# Build geth before harness; the latter depends on the former.
docker build -t quorum-raft ./docker-quorum/
docker build -t quorum-harness ./docker-harness/

rm docker-quorum/id_noirqs
rm docker-harness/id_noirqs
rm docker-quorum/github.pub
rm docker-harness/github.pub
